### ISSUE TITLE
feature: exclusive operator

### ISSUE THREAD

**Issue by musjj** [folke/flash.nvim#49]
### Did you check the docs?

- [X] I have read all the flash.nvim docs

### Is your feature request related to a problem? Please describe.

When doing directional jumps in an operator pending mode, like this:
```lua
require("flash").jump {
  search = { forward = true, wrap = false, multi_window = false },
}
```
You sometimes want to *exclude* the target from the operation, similar to operations like `dtw`

### Describe the solution you'd like

An option to make the jump behave like an exclusive operator.

### Describe alternatives you've considered

Currently, I don't think there's an option that can simulate this behavior.

**Comment by folke** [comment]
I added a new option `opts.jump.inclusive`
By default it is `nil` meaning it will be automatically set based on the mode you're in.

You can set it to `true`/`false` to force inclusive/exclusive

**Comment by musjj** [comment]
Thanks, but it seems that the snippet in my original post no longer works (it doesn't seem to do anything). A plain `require("flash").jump()` still works, though.

**Comment by folke** [comment]
Damn, you're right. On it

**Comment by folke** [comment]
Fixed now. Sorry about that :)

**Comment by musjj** [comment]
Thanks, it's working! But with backward jumps, it seems that it always jumps to the beginning of the match.

For example, using the following config:

```lua
require("flash").jump(
    search = { forward = false, wrap = false, multi_window = false },
    jump = { inclusive = false }
)
```

With the following text, the cursor at `^`
```
The quick brown fox jumped over the lazy dog.
                               ^
```
While using the `d` operation, and the candidate `ed`, you will get:
```diff
- The quick brown fox jumped over the lazy dog.
+ The quick brown fox jump the lazy dog.
```
What I expect:
```diff
- The quick brown fox jumped over the lazy dog.
+ The quick brown fox jumped the lazy dog.
```

**Comment by folke** [comment]
You should add `jump.pos = "end"`

**Comment by musjj** [comment]
Thank you! With this, `flash.nvim` has reached feature-parity (plus more) with `leap.nvim` :)

**Comment by musjj** [comment]
Sorry for being a party pooper, but it turns out that it's still not working quite right.
The following performed on operator-pending mode:
```lua
require("flash").jump { 
  search = { forward = false, wrap = false, multi_window = false },
  jump = { inclusive = false, pos = "end" },
}
```
Doesn't exclude the last character of the match.

**Comment by folke** [comment]
I added `jump.offset`, but when using `pos="end"` and the jump position is before the current position, it will default to `1`.

You also probably still want to use `inclusive` mode.

So you should change it to:

```lua
require("flash").jump { 
  search = { forward = false, wrap = false, multi_window = false },
  jump = { pos = "end" },
}
```

This should now work as expected.

Let me know if it does! :)

**Comment by musjj** [comment]
Thanks, it's working perfectly!
